server:
  port: 8080
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "10s"

client:
  timeout: "10s"

database:
  host: "localhost" # postgres - Docker, localhost - local
  port: 5432
  user: "postgres"
  password: "postgres" 
  name: "weather"
  ssl_mode: "disable"

cron:
  update_interval: "15m"
  cities:
    - "Moscow"
    - "London"
    - "New York"
    - "Tokyo"
    - "Berlin"
    - "Paris"
    - "Rome"
    - "Madrid"
    - "Beijing"
    - "Sydney"

logger:
 level: "debug"

migrations: 
  dir: "./migrations"